CREATE TABLE [dbo].[DreamText]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1), 
    [AspId] NVARCHAR (128) NOT NULL, 
    [Date] DATETIME NOT NULL, 

    [Summary] TEXT NOT NULL, 
    [Lucid] VARCHAR(20) NOT NULL, 
    [NScenes] INT NOT NULL, 
    [NDirectPeople] INT NOT NULL, 
    [NBackgroundPeople] INT NOT NULL, 
    [NKnownPeople] INT NOT NULL, 
    [NFantasyCharacters] INT NOT NULL, 
    [NArchitypicalCharacters] INT NOT NULL, 
    [NFalseAwakenings] INT NOT NULL, 
    [Fly] VARCHAR(20) NOT NULL, 
    [Run] VARCHAR(20) NOT NULL, 
    [TFly] INT NOT NULL, 
    [TRun] INT NOT NULL, 
    [Control] DECIMAL(5, 2) NOT NULL, 
    [Relate] DECIMAL(5, 2) NOT NULL, 
    [Real] DECIMAL(5, 2) NOT NULL, 
    [Yourself] DECIMAL(5, 2) NOT NULL, 
    [Colorful] DECIMAL(5, 2) NOT NULL, 
    [RecogniseSurroundings] DECIMAL(5, 2) NOT NULL, 
    [PastMemories] DECIMAL(5, 2) NOT NULL, 
    [Emotion] DECIMAL(5, 2) NOT NULL, 
    [Conflict] DECIMAL(5, 2) NOT NULL, 
    [Resolution] DECIMAL(5, 2) NOT NULL, 
    [RelatedConflict] DECIMAL(5, 2) NOT NULL, 
    [Prophetic] DECIMAL(5, 2) NOT NULL, 
    [Spiritual] DECIMAL(5, 2) NOT NULL, 
    [Rating] DECIMAL(5, 2) NOT NULL, 
    [Insight] DECIMAL(5, 2) NOT NULL, 
    [Length] INT NOT NULL, 
    [DetailedText] TEXT NULL, 
    CONSTRAINT [FK_Table_ToAspNetUsers] FOREIGN KEY ([AspId]) REFERENCES [AspNetUsers]([Id])
)
