//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucidDreamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int Id { get; set; }
        public string AspId { get; set; }
        public System.DateTime Date { get; set; }
        public string Summary { get; set; }
        public int Sleep { get; set; }
        public int MorningTime { get; set; }
        public int BedTime { get; set; }
        public int Meditation { get; set; }
        public string Exercise { get; set; }
        public string Breakfast { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
        public decimal Energy { get; set; }
        public decimal Motivation { get; set; }
        public decimal Emotion { get; set; }
        public decimal Productive { get; set; }
        public string Goal1 { get; set; }
        public string Goal2 { get; set; }
        public string Goal3 { get; set; }
        public string PlanSummary { get; set; }
        public decimal Rating { get; set; }
        public string Notes { get; set; }
    }
}
