//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucidDreamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamText
    {
        public int Id { get; set; }
        public string AspId { get; set; }
        public System.DateTime Date { get; set; }
        public string Summary { get; set; }
        public string Lucid { get; set; }
        public int NScenes { get; set; }
        public int NDirectPeople { get; set; }
        public int NBackgroundPeople { get; set; }
        public int NKnownPeople { get; set; }
        public int NFantasyCharacters { get; set; }
        public int NArchitypicalCharacters { get; set; }
        public int NFalseAwakenings { get; set; }
        public string Fly { get; set; }
        public string Run { get; set; }
        public int TFly { get; set; }
        public int TRun { get; set; }
        public decimal Control { get; set; }
        public decimal Relate { get; set; }
        public decimal Real { get; set; }
        public decimal Yourself { get; set; }
        public decimal Colorful { get; set; }
        public decimal RecogniseSurroundings { get; set; }
        public decimal PastMemories { get; set; }
        public decimal Emotion { get; set; }
        public decimal Conflict { get; set; }
        public decimal Resolution { get; set; }
        public decimal RelatedConflict { get; set; }
        public decimal Prophetic { get; set; }
        public decimal Spiritual { get; set; }
        public decimal Rating { get; set; }
        public decimal Insight { get; set; }
        public int Length { get; set; }
        public string DetailedText { get; set; }
    }
}
