//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucidDreamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string AspId { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> DreamEntries { get; set; }
        public Nullable<int> DiaryEntries { get; set; }
        public string MainGoal { get; set; }
        public string Image { get; set; }
    }
}
